const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#A855F7",
    background: "#05020A",
    foreground: "#FFFFFF",
    card: "#110C1E",
    cardForeground: "#FFFFFF",
    primary: "#A855F7",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1035",
    secondaryForeground: "#FFFFFF",
    muted: "#1E1035",
    mutedForeground: "#9CA3AF",
    accent: "#EC4899",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D1B69",
    input: "#1E1035",
    gold: "#F59E0B",
    goldGlow: "#FCD34D",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#A855F7",
    background: "#05020A",
    foreground: "#FFFFFF",
    card: "#110C1E",
    cardForeground: "#FFFFFF",
    primary: "#A855F7",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1035",
    secondaryForeground: "#FFFFFF",
    muted: "#1E1035",
    mutedForeground: "#9CA3AF",
    accent: "#EC4899",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D1B69",
    input: "#1E1035",
    gold: "#F59E0B",
    goldGlow: "#FCD34D",
  },
  radius: 16,
};

export default colors;
